"""add users, user_identities and user_id fks

Revision ID: 83ccf89062d9
Revises: 34505e022815
Create Date: 2026-07-21 14:45:15.671748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ccf89062d9'
down_revision: Union[str, Sequence[str], None] = '34505e022815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=25), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_id')
    )
    op.create_index(op.f('ix_user_identities_platform'), 'user_identities', ['platform'], unique=False)
    op.create_index(op.f('ix_user_identities_platform_id'), 'user_identities', ['platform_id'], unique=False)
    with op.batch_alter_table('budgets') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_budgets_user_id', 'users', ['user_id'], ['id'])
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_constraint('fk_transactions_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_column('user_id')
    with op.batch_alter_table('budgets') as batch_op:
        batch_op.drop_constraint('fk_budgets_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_column('user_id')
    op.drop_index(op.f('ix_user_identities_platform_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_platform'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('users')
    # ### end Alembic commands ###
